---
title: "Autocorrelation Only noise"
author: "Tomas Lenc"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: 
      collapsed: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source('config.R')

```

```{r}
# list.files(data_path)
```


```{r}

df_only_noise <- read.csv(file.path(data_path, 'onlyNoise_noise-eeg_nrep-1000.csv'))

df_only_noise$sample <- seq(1, nrow(df_only_noise))
    
library(tidyr)
df_only_noise_long <- pivot_longer(df_only_noise,
                                   !sample, 
                                   names_to='condition',
                                   values_to='z_meter')

```



```{r}

library(BayesFactor)
library(Rmisc)
library(dplyr)

bf <- BayesFactor::ttestBF(df_only_noise$fft_subtr, mu=0)

get_bf <- function(df) {
       bf <- ttestBF(df$z_meter, mu=0)
       data.frame(bf10 = sprintf('BF10=%.3g', as.vector(bf)),
                  z_meter=0.05 + max(df$z_meter))
}

df_bf <- df_only_noise_long %>% 
    group_by(condition) %>%
    group_modify(~ get_bf(.x))

df_summary <- summarySE(data=df_only_noise_long, measurevar='z_meter', groupvars=c('condition'))


```


```{r}
library(ggplot2)
library(gghalves)
library(cowplot)

ggplot(df_only_noise_long, aes(x=1, y=z_meter)) + 
    geom_hline(yintercept=0, color='black', linetype='dashed') + 
    geom_half_violin(side='l', scale='width', fill='grey70', color=NA) + 
    geom_half_point(side='r', color='grey50', alpha=0.1) + 
    geom_point(data=df_summary, size=2, color='black') + 
    geom_errorbar(data=df_summary, aes(ymin=z_meter-sd, ymax=z_meter+sd),
                  color='black', linewidth=0.8, width=0) + 
    geom_text(data=df_bf, aes(label=bf10)) + 
    scale_x_continuous(breaks=c()) + 
    facet_wrap(~condition, nrow=1, scales='free_y') + 
    theme_cowplot() + 
    theme(
        axis.title.x = element_blank(),
        axis.line.x = element_blank()
    )

```




---


```{r}

fun_plot <- function(fname, yvar) {
    df <- read.csv(file.path(data_path, fname))
    df$pat <- factor(df$pat)
    df <- filter(df, z_snr > 0)
    ggplot(df, aes(log10(z_snr), .data[[yvar]])) +
    # geom_point(alpha=0.1, color='#701d85') + 
    geom_point(aes(color=pat), alpha=0.1) + 
    geom_hline(yintercept = 0, color='#5e5e5e') + 
    # coord_cartesian(xlim=c(0,100)) + 
    scale_x_reverse() +
    theme_cowplot()
}

```



<br><br><br>

## IR erp2

### FFT  

```{r}
fname <- 'irType-erp2_nrep-100_emphVsNoise.csv'
fun_plot(fname, 'z_meter_fft_raw')
fun_plot(fname, 'z_meter_fft_subtr')
```

### ACF  

```{r}
fun_plot(fname, 'z_meter_acf_raw')
fun_plot(fname, 'z_meter_acf_subtr')
```





<br><br><br>

## IR square

### FFT  

```{r}
fname <- 'irType-square_nrep-100_emphVsNoise.csv'
fun_plot(fname, 'z_meter_fft_raw')
fun_plot(fname, 'z_meter_fft_subtr')
```

### ACF  

```{r}
fun_plot(fname, 'z_meter_acf_raw')
fun_plot(fname, 'z_meter_acf_subtr')
```

































