---
title: "Autocorrelation SNR vs. number of lags/frex"
author: "Tomas Lenc"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: 
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source('config.R')
source('figures.R')
source('utils.R')

```

```{r}

data_path <- file.path(experiment_path, 'data')

list.files(data_path)
```


```{r}

df <- read.csv(file.path(data_path, 'irType-erp2_nrep-500_snrVsNlagsNfrex.csv'))

df$max_lag <- factor(df$max_lag)
df$snr <- factor(round(df$snr, 1))
df$sample <- factor(df$sample)

df$max_lag <- revalue(df$max_lag, c("4.8"="low", "24"="high"))

```


```{r, fig.width=7, fig.height=5}

col_scale <- scale_color_brewer(palette='Paired')

plot_data <- function(df, col_name, col_name_orig){
    
    df$x <- as.numeric(df$snr)
    df$x_orig_start <- df$x-0.3
    df$x_orig_end <- df$x+0.3
    
    # df$y <- df[, col_name] - df[, col_name_orig]
    
    p <- ggplot(df, aes(x, .data[[col_name]])) + 
        # geom_segment(aes(x=x_orig_start, xend=x_orig_end,
        #                  y=.data[[col_name_orig]], yend=.data[[col_name_orig]]),
        #              size=3, alpha=0.5, color='grey70') +
        geom_hline(yintercept=0, linewidth=1, color='black', alpha=1, linetype='dotted') + 
        geom_hline(aes(yintercept=.data[[col_name_orig]]), linewidth=3, color='red', alpha=0.4) + 
        # geom_point(alpha=0.3, position=position_jitter(height=0, width=0.2)) +
        geom_half_violin(aes(group=snr), side='l', scale='width',
                         fill='grey60', color=NA, alpha=1, trim=T) + 
        geom_half_point(aes(group=snr), side='r', alpha=0.1, color='black') + 
        ylab(paste(col_name, '(dist from true)')) + 
        facet_wrap(~ max_lag, nrow=2) + 
        theme_cowplot()
    
    return(p)

}


plot_bias_var <- function(df, col_name, col_name_orig){
    
    df$x <- as.numeric(df$snr)
    
    df$y <- df[, col_name] - df[, col_name_orig]
    
    df_bias_var <- df %>% 
        group_by(max_lag, snr) %>% 
        summarise(bias=mean(y), 
                  bias_ci=sd(y) / sqrt(n()) * qnorm(1 - 0.05), 
                  variance=var(y))
    
    pos <- position_dodge(0.1)
    p1 <- ggplot(df_bias_var, aes(snr, bias, group=max_lag, color=max_lag)) + 
        geom_hline(yintercept=0, linewidth=1, color='red', alpha=1, linetype='dotted') + 
        geom_point(position=pos) + 
        geom_errorbar(aes(ymin=bias-bias_ci, ymax=bias+bias_ci),
                      position=pos, linewidth=1, width=0) + 
        geom_line(position=pos) + 
        col_scale + 
        theme_cowplot() + 
        theme(
            legend.position = 'none'
        )
    
    p2 <- ggplot(df_bias_var, aes(snr, variance, group=max_lag, color=max_lag)) + 
        geom_hline(yintercept=0, linewidth=1, color='red', alpha=1, linetype='dotted') + 
        geom_point() + 
        geom_line() + 
        col_scale + 
        theme_cowplot()
    
    p <- ggarrange(p1, p2, nrow=2, common.legend=TRUE, legend="right")
    
    return(p)
}
```



```{r, fig.width=10, fig.height=5.5}

# col_name <- 'z_meter_acf_subtr'
# col_name_orig <- 'z_meter_acf_orig'

p1 <- plot_data(df,  'z_meter_acf_subtr', 'z_meter_acf_orig')
p2 <- plot_bias_var(df,  'z_meter_acf_subtr', 'z_meter_acf_orig')
plot_grid(p1, p2, rel_widths=c(60, 40))
```



```{r, fig.width=10, fig.height=5.5}

p1 <- plot_data(df,  'z_meter_fft_subtr', 'z_meter_fft_orig')
p2 <- plot_bias_var(df,  'z_meter_fft_subtr', 'z_meter_fft_orig')
plot_grid(p1, p2, rel_widths=c(60, 40))
```




