---
title: "Autocorrelation SyncRange"
author: "Tomas Lenc"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: 
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source('config.R')
source('figures.R')
source('utils.R')

```

```{r}

data_path <- file.path(experiment_path, 'data')

list.files(data_path)
```


```{r}
rhythms <- c('31', '26', '19', '37', '42', '6', '17', '41')

df_eeg_boot <- read.csv(file.path(data_path, 'exp-syncrange_eegBoot.csv'))
df_eeg_grand <- read.csv(file.path(data_path, 'exp-syncrange_eegGrand.csv'))
df_eeg_ind <- read.csv(file.path(data_path, 'exp-syncrange_eegIndividual.csv'))
df_tap <- read.csv(file.path(data_path, 'exp-syncrange_tapping.csv'))

df_eeg_boot$rhythm <- factor(df_eeg_boot$rhythm,  levels=rhythms)
df_eeg_grand$rhythm <- factor(df_eeg_grand$rhythm,  levels=rhythms)
df_eeg_ind$rhythm <- factor(df_eeg_ind$rhythm,  levels=rhythms)
df_tap$rhythm <- factor(df_tap$rhythm,  levels=rhythms)

# df_eeg_boot$n_trials <- as.factor(df_eeg_boot$n_trials)

```


<br>

---

## FFT ~ ACF

<br><br>

### EEG bootstrap

```{r, fig.width=4, fig.height=4}

df <- filter(df_eeg_boot, n_trials==9)

res <- cor.test(df$z_meter_fft_subtr, df$z_meter_acf_subtr, method='spearman')

p <- plot_correlation_scatter(df, 'z_meter_fft_subtr', 'z_meter_acf_subtr', corr_result=res)

save_fig(file.path(fig_path, 'exp-syncsweep_response-eeg_fftAcfCorr'), p, width=4, height=4)

p

```



```{r}
df <- filter(df_eeg_boot, n_trials==9)

m <- lm(z_meter_acf_subtr ~ z_meter_fft_subtr + rhythm, data=df)
summary(m)
```

```{r, fig.width=5, fig.height=5}
visreg(m, 'z_meter_fft_subtr', by='rhythm', overlay=T)
```

Even the amount of selective enhancement of meter compared to the sound is correlated across the two measures.  

```{r}
df <- filter(df_eeg_boot, n_trials==9)
df$z_meter_fft_eeg_minus_sound <- df$z_meter_fft_subtr - df$z_meter_fft_sound
df$z_meter_acf_eeg_minus_sound <- df$z_meter_acf_subtr - df$z_meter_acf_sound
    
m <- lm(z_meter_acf_eeg_minus_sound ~ z_meter_fft_eeg_minus_sound + rhythm, data=df)
summary(m)
```

```{r, fig.width=5, fig.height=5}
visreg(m, 'z_meter_fft_eeg_minus_sound', by='rhythm', overlay=T)
```



### EEG individual 

```{r}

cols <- RColorBrewer::brewer.pal(8, 'Set1')    
cols_individual <- lighten(cols, amount=0.7)
names(cols) <- rhythms
names(cols_individual) <- rhythms

plot_feat_ind <- function(df, 
                         col_name_eeg='z_meter_fft_subtr', col_name_coch='z_meter_fft_sound'){
    
    df$x <- as.numeric(df$rhythm)
    df$x_coch_start <- df$x-0.3
    df$x_coch_end <- df$x+0.3
    
    df_summary <- summarySE(df, groupvars=c('rhythm'), 
                             measurevar=col_name_eeg)
    
    df_summary$x <- as.numeric(df_summary$rhythm)
    
    p <- ggplot(df, aes(x, .data[[col_name_eeg]], color=rhythm)) + 
        geom_segment(data=df[df$subject==df$subject[1],],
                     inherit.aes=FALSE,
                     aes(x=x_coch_start, xend=x_coch_end,
                         y=.data[[col_name_coch]], yend=.data[[col_name_coch]],
                         color=rhythm),
                     size=3, alpha=0.5) +
        scale_color_manual(name='rhythm', values=cols) +
        scale_x_continuous(breaks=c(1:length(levels(df$rhythm))), 
                           labels=levels(df$rhythm)) +  
        new_scale_color() + new_scale_fill() +
        geom_point(aes(color=rhythm), size=2, position=position_jitter(width=0.1, height=0)) +
        scale_color_manual(name='rhythm', values=cols_individual) + 
        geom_hline(yintercept=0) +
        new_scale_color() + new_scale_fill() + 
        geom_point(data=df_summary, aes(color=rhythm), size=3) + 
        geom_errorbar(data=df_summary, 
                      aes(color=rhythm, ymin=.data[[col_name_eeg]]-ci,
                          ymax=.data[[col_name_eeg]]+ci), 
                      size=1, width=0.2) + 
        scale_color_manual(name='rhythm', values=cols) + 
        theme_cowplot() + 
        my_theme()
    
    return(p)
}

plot_feat_ind(df_eeg_ind)

```
```{r}

cols <- pal_d3()(9)[c(1:7, 9)]
names(cols) <- rhythms

df <- df_eeg_grand
df_boot <- df_eeg_boot %>% filter(n_trials==9)
col_name_eeg='z_meter_fft_subtr' 
col_name_coch='z_meter_fft_sound'

plot_feat_ind <- function(df, df_boot, col_name_eeg='z_meter_fft_subtr', col_name_coch='z_meter_fft_sound'){
    
    df$x <- as.numeric(df$rhythm)
    df$x_coch_start <- df$x-0.4
    df$x_coch_end <- df$x+0.4
    
    df_boot$x <- as.numeric(df_boot$rhythm)
    
    df_ci <- df_boot %>% 
        group_by(n_trials, rhythm) %>% 
        group_modify(~ get_boot_summary(.x, .y, feature_name=col_name_eeg)) 
        
    df_summary <- join(df_ci, 
                       df %>% select(n_trials, rhythm, x, 
                                     x_coch_start, x_coch_end, 
                                     .data[[col_name_eeg]], .data[[col_name_coch]]), 
                       by=c('n_trials', 'rhythm'))
    
    p <- ggplot(df_summary, aes(x, .data[[col_name_eeg]], color=rhythm)) + 
        geom_segment(aes(x=x_coch_start, xend=x_coch_end,
                         y=.data[[col_name_coch]], yend=.data[[col_name_coch]],
                         color=rhythm),
                     size=3, alpha=0.5) +
        scale_color_manual(name='rhythm', values=cols)+
        scale_fill_manual(name='rhythm', values=cols) +
        scale_x_continuous(breaks=c(1:length(levels(df$rhythm))), 
                           labels=levels(df$rhythm)) +  
        # geom_point(data=df_boot, aes(color=rhythm), 
        #            size=2, position=position_jitter(width=0.2, height=0), alpha=0.01) +
        geom_half_violin(data=df_boot, aes(fill=rhythm, group=rhythm), 
                         side='l', scale='width', fill='grey60', color=NA, alpha=0.6, trim=T) + 
        # geom_half_point(data=df_boot, aes(color=rhythm),
        #                 side='r', alpha=0.01, color='grey70') + 
        geom_hline(yintercept=0) +
        geom_point(aes(x=x+0.15, color=rhythm), size=3) + 
        geom_errorbar(aes(x=x+0.15, color=rhythm, ymin=ci_low, ymax=ci_high), 
                      size=1, width=0) + 
        theme_cowplot() + 
        my_theme()
    
    return(p)
}

plot_feat_ind(df_eeg_grand, 
              df_eeg_boot %>% filter(n_trials==9), 
              col_name_eeg='z_meter_acf_subtr',
              col_name_coch='z_meter_acf_sound')


```

```{r, fig.width=4, fig.height=4}

res <- cor.test(df_eeg_ind$z_meter_fft_subtr, 
                df_eeg_ind$z_meter_acf_subtr, 
                method='spearman')

p <- plot_correlation_scatter(df_eeg_ind, 
                              'z_meter_fft_subtr',
                              'z_meter_acf_subtr',
                              corr_result=res)

save_fig(file.path(fig_path, 'exp-syncsweep_response-eegInd_fftAcfCorr'), 
         p, width=4, height=4)

print(p)
```

```{r}
m <- lm(z_meter_acf_subtr ~ z_meter_fft_subtr + rhythm, data=df_eeg_ind)
summary(m)
```

```{r, fig.width=5, fig.height=5}
visreg(m, 'z_meter_fft_subtr', by='rhythm', overlay=T)
```




<br><br><br>

### Tapping 

```{r, fig.width=4, fig.height=4}

res <- cor.test(df_tap$z_meter_fft_raw, df_tap$z_meter_acf_raw, method='spearman')

p <- plot_correlation_scatter(df_tap, 'z_meter_fft_raw', 'z_meter_acf_raw', corr_result=res)

save_fig(file.path(fig_path, 'exp-syncsweep_response-tap_fftAcfCorr'), p, width=4, height=4)

p
```




```{r}
m <- lm(z_meter_acf_raw ~ z_meter_fft_raw + rhythm, data=df_tap)
summary(m)
```

```{r, fig.width=5, fig.height=5}
visreg(m, 'z_meter_fft_raw', by='rhythm', overlay=T)
```






<br><br><br><br><br>

---

## Low SNR pushes z to 0

```{r}
m <- lm(z_meter_fft_subtr ~ n_trials * z_meter_fft_sound, data=df_eeg_boot)
summary(m)
```

```{r}
visreg(m, 'n_trials', by='z_meter_fft_sound', overlay=F)
```



```{r}
m <- lm(z_meter_acf_subtr ~ n_trials * z_meter_acf_sound, data=df_eeg_boot)
summary(m)
```

```{r}
visreg(m, 'n_trials', by='z_meter_acf_sound', overlay=F)
```


```{r}

plot_snr_effect <- function(df, yvar) {
    df <- df_eeg_boot
    df$n_trials <- as.numeric(df$n_trials)
    p <- ggplot(df_eeg_boot, aes(n_trials, .data[[yvar]], color=n_trials)) + 
        geom_point() + 
        geom_hline(yintercept = 0, color='#5e5e5e') + 
        scale_x_reverse(breaks=c(9,1)) +
        # scale_color_distiller(direction=1, palette='Purples') + 
        scale_color_gradient(high='#701d85', low='#f0c0fc', breaks=c(1,9)) + 
        facet_grid(~rhythm) + 
        guides(color = guide_colourbar(ticks = FALSE)) + 
        theme_cowplot() + 
        theme(
            axis.line.x = element_blank(),
            axis.title.x = element_blank(),
            axis.ticks.x = element_blank(),
            axis.text.x = element_blank()
        )
    return(p)
}

```

```{r}
p_fft <- plot_snr_effect(df_eeg_boot, 'z_meter_fft_subtr') 
save_fig(file.path(fig_path, 'exp-syncsweep_response-eeg_fftSnrEffect'), p_fft, width=7, height=4)
p_fft
```

```{r}
p_acf <- plot_snr_effect(df_eeg_boot, 'z_meter_acf_subtr') 
save_fig(file.path(fig_path, 'exp-syncsweep_response-eeg_acfSnrEffect'), p_acf, width=7, height=4)
p_acf
```



















