---
title: "Autocorrelation LowHigh"
author: "Tomas Lenc"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: 
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source('config.R')
source('figures.R')
source('utils.R')

```

```{r}
# list.files(data_path)
```


```{r}
rhythms <- c('unsyncopated', 'syncopated')
tones <- c('L', 'H')

df_eeg_boot <- read.csv(file.path(data_path, 'exp-lowhigh_eegBoot.csv'))
df_eeg_grand <- read.csv(file.path(data_path, 'exp-lowhigh_eegGrand.csv'))
df_eeg_ind <- read.csv(file.path(data_path, 'exp-lowhigh_eegIndividual.csv'))

df_eeg_boot$rhythm <- factor(df_eeg_boot$rhythm,  levels=rhythms)
df_eeg_grand$rhythm <- factor(df_eeg_grand$rhythm,  levels=rhythms)
df_eeg_ind$rhythm <- factor(df_eeg_ind$rhythm,  levels=rhythms)

df_eeg_boot$tone <- factor(df_eeg_boot$tone,  levels=tones)
df_eeg_grand$tone <- factor(df_eeg_grand$tone,  levels=tones)
df_eeg_ind$tone <- factor(df_eeg_ind$tone,  levels=tones)
```


<br>

### EEG individual 

```{r}

cols <- c(L='red', H='blue')
cols_individual <- lighten(cols, amount=0.7)
names(cols_individual) <- names(cols)

df <- df_eeg_ind
col_name_eeg='z_meter_acf_subtr'
col_name_coch='z_meter_acf_sound'

plot_feat_ind <- function(df, 
                         col_name_eeg='z_meter_fft_subtr', col_name_coch='z_meter_fft_sound'){
    
    df$x <- as.numeric(df$tone)
    df$x_coch_start <- df$x-0.3
    df$x_coch_end <- df$x+0.3
    
    df_summary <- summarySE(df, groupvars=c('rhythm', 'tone'), measurevar=col_name_eeg)
    
    df_summary$x <- as.numeric(df_summary$tone)
    
    p <- ggplot(df, aes(x, .data[[col_name_eeg]], color=tone)) + 
        geom_segment(data=df[df$subject==df$subject[1],],
                     inherit.aes=FALSE,
                     aes(x=x_coch_start, xend=x_coch_end,
                         y=.data[[col_name_coch]], yend=.data[[col_name_coch]],
                         color=tone),
                     linewidth=3, alpha=0.5) +
        scale_color_manual(name='tone', values=cols) +
        scale_x_continuous(breaks=c(1:length(levels(df$tone))), 
                           labels=levels(df$tone)) +  
        new_scale_color() + new_scale_fill() +
        geom_point(aes(color=tone), size=2, position=position_jitter(width=0.1, height=0)) +
        scale_color_manual(name='tone', values=cols_individual) + 
        geom_hline(yintercept=0) +
        new_scale_color() + new_scale_fill() + 
        geom_point(data=df_summary, aes(color=tone), size=3) + 
        geom_errorbar(data=df_summary, 
                      aes(color=tone, ymin=.data[[col_name_eeg]]-ci,
                          ymax=.data[[col_name_eeg]]+ci), 
                      linewidth=1, width=0.2) + 
        scale_color_manual(name='tone', values=cols) + 
        facet_wrap(~rhythm, nrow=1) + 
        theme_cowplot() + 
        my_theme()
    
    return(p)
}


# df <- df_eeg_grand
# df_boot <- df_eeg_boot %>% filter(n_trials==9)
# col_name_eeg='z_meter_fft_subtr' 
# col_name_coch='z_meter_fft_sound'

plot_feat_boot <- function(df, df_boot, col_name_eeg='z_meter_fft_subtr', col_name_coch='z_meter_fft_sound'){

    df$x <- as.numeric(df$rhythm)
    df$x_coch_start <- df$x-0.4
    df$x_coch_end <- df$x+0.4
    
    df_boot$x <- as.numeric(df_boot$rhythm)
    
    df_ci <- df_boot %>% 
        group_by(n_trials, rhythm) %>% 
        group_modify(~ get_boot_summary(.x, .y, feature_name=col_name_eeg)) 
        
    df_summary <- join(df_ci, 
                       df %>% select(n_trials, rhythm, x, 
                                     x_coch_start, x_coch_end, 
                                     .data[[col_name_eeg]], .data[[col_name_coch]]), 
                       by=c('n_trials', 'rhythm'))
    
    p <- ggplot(df_summary, aes(x, .data[[col_name_eeg]], color=rhythm)) + 
        geom_segment(aes(x=x_coch_start, xend=x_coch_end,
                         y=.data[[col_name_coch]], yend=.data[[col_name_coch]],
                         color=rhythm),
                     linewidth=3, alpha=0.5) +
        scale_color_manual(name='rhythm', values=cols)+
        scale_fill_manual(name='rhythm', values=cols) +
        scale_x_continuous(breaks=c(1:length(levels(df$rhythm))), 
                           labels=levels(df$rhythm)) +  
        # geom_point(data=df_boot, aes(color=rhythm), 
        #            size=2, position=position_jitter(width=0.2, height=0), alpha=0.01) +
        geom_half_violin(data=df_boot, aes(fill=rhythm, group=rhythm), 
                         side='l', scale='width', fill='grey60', color=NA, alpha=0.6, trim=T) + 
        # geom_half_point(data=df_boot, aes(color=rhythm),
        #                 side='r', alpha=0.01, color='grey70') + 
        geom_hline(yintercept=0) +
        geom_point(aes(x=x+0.15, color=rhythm), size=3) + 
        geom_errorbar(aes(x=x+0.15, color=rhythm, ymin=ci_low, ymax=ci_high), 
                      size=1, width=0) + 
        theme_cowplot() + 
        my_theme()
    
    return(p)
}

```

```{r}

plot_feat_ind(df_eeg_ind, 
              col_name_eeg='z_meter_acf_subtr',
              col_name_coch='z_meter_acf_sound')

```

```{r}

plot_feat_boot(df_eeg_grand, 
              df_eeg_boot %>% filter(n_trials==9), 
              col_name_eeg='z_meter_acf_subtr',
              col_name_coch='z_meter_acf_sound')


```

```{r, fig.width=4, fig.height=4}

res <- cor.test(df_eeg_ind$z_meter_fft_subtr, 
                df_eeg_ind$z_meter_acf_subtr, 
                method='spearman')

p <- plot_correlation_scatter(df_eeg_ind, 
                              'z_meter_fft_subtr',
                              'z_meter_acf_subtr',
                              corr_result=res)

save_fig(file.path(fig_path, 'exp-syncsweep_response-eegInd_fftAcfCorr'), 
         p, width=4, height=4)

print(p)
```

```{r}
m <- lm(z_meter_acf_subtr ~ z_meter_fft_subtr + rhythm, data=df_eeg_ind)
summary(m)
```

```{r, fig.width=5, fig.height=5}
visreg(m, 'z_meter_fft_subtr', by='rhythm', overlay=T)
```




<br><br><br>

### Tapping 

```{r, fig.width=4, fig.height=4}

res <- cor.test(df_tap$z_meter_fft_raw, df_tap$z_meter_acf_raw, method='spearman')

p <- plot_correlation_scatter(df_tap, 'z_meter_fft_raw', 'z_meter_acf_raw', corr_result=res)

save_fig(file.path(fig_path, 'exp-syncsweep_response-tap_fftAcfCorr'), p, width=4, height=4)

p
```




```{r}
m <- lm(z_meter_acf_raw ~ z_meter_fft_raw + rhythm, data=df_tap)
summary(m)
```

```{r, fig.width=5, fig.height=5}
visreg(m, 'z_meter_fft_raw', by='rhythm', overlay=T)
```






<br><br><br><br><br>

---

## Low SNR pushes z to 0

```{r}
m <- lm(z_meter_fft_subtr ~ n_trials * z_meter_fft_sound, data=df_eeg_boot)
summary(m)
```

```{r}
visreg(m, 'n_trials', by='z_meter_fft_sound', overlay=F)
```



```{r}
m <- lm(z_meter_acf_subtr ~ n_trials * z_meter_acf_sound, data=df_eeg_boot)
summary(m)
```

```{r}
visreg(m, 'n_trials', by='z_meter_acf_sound', overlay=F)
```


```{r}

plot_snr_effect <- function(df, yvar, yvar_coch) {
    df <- df_eeg_boot
    df$n_trials <- as.numeric(df$n_trials)
    p <- ggplot(df_eeg_boot, aes(z_snr, .data[[yvar]])) + 
        geom_hline(aes(yintercept=.data[[yvar_coch]]), linewidth=3, alpha=0.5) + 
        geom_point(alpha=0.01, color='#701d85') + 
        geom_hline(yintercept = 0, color='#5e5e5e') + 
        scale_x_reverse() +
        # scale_color_gradient(high='#701d85', low='#0f0412') + 
        facet_grid(~rhythm) + 
        guides(color = guide_colourbar(ticks = FALSE)) + 
        theme_cowplot() + 
        theme(
            axis.line.x = element_blank(),
            axis.title.x = element_blank(),
            axis.ticks.x = element_blank(),
            axis.text.x = element_blank()
        )
    return(p)
}

```

```{r, fig.width=12, fig.height=4}
p_fft <- plot_snr_effect(df_eeg_boot, 'z_meter_fft_subtr', 'z_meter_fft_sound') 
save_fig(file.path(fig_path, 'exp-syncsweep_response-eeg_fftSnrEffect'), p_fft, width=7, height=4)
p_fft
```

```{r, fig.width=12, fig.height=4}
p_acf <- plot_snr_effect(df_eeg_boot, 'z_meter_acf_subtr', 'z_meter_acf_sound') 
save_fig(file.path(fig_path, 'exp-syncsweep_response-eeg_acfSnrEffect'), p_acf, width=7, height=4)
p_acf
```



















