---
title: "Autocorrelation Only noise"
author: "Tomas Lenc"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: 
      collapsed: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source('config.R')

```

```{r}
# list.files(data_path)
```


```{r}

df_only_noise <- read.csv(file.path(data_path, 'onlyNoise_noise-eeg_nrep-1000.csv'))

df_only_noise$sample <- seq(1, nrow(df_only_noise))
    
library(tidyr)
df_only_noise_long <- pivot_longer(df_only_noise,
                                   !sample, 
                                   names_to='condition',
                                   values_to='z_meter')

```



```{r}

library(BayesFactor)
library(Rmisc)
library(dplyr)

bf <- BayesFactor::ttestBF(df_only_noise$fft_subtr, mu=0)

get_bf <- function(df) {
       bf <- ttestBF(df$z_meter, mu=0)
       data.frame(bf10 = sprintf('BF10=%.3g', as.vector(bf)),
                  z_meter=0.05 + max(df$z_meter))
}

df_bf <- df_only_noise_long %>% 
    group_by(condition) %>%
    group_modify(~ get_bf(.x))

df_summary <- summarySE(data=df_only_noise_long, measurevar='z_meter', groupvars=c('condition'))


```


```{r}
library(ggplot2)
library(gghalves)
library(cowplot)

ggplot(df_only_noise_long, aes(x=1, y=z_meter)) + 
    geom_hline(yintercept=0, color='black', linetype='dashed') + 
    geom_half_violin(side='l', scale='width', fill='grey70', color=NA) + 
    geom_half_point(side='r', color='grey50', alpha=0.1) + 
    geom_point(data=df_summary, size=2, color='black') + 
    geom_errorbar(data=df_summary, aes(ymin=z_meter-sd, ymax=z_meter+sd),
                  color='black', linewidth=0.8, width=0) + 
    geom_text(data=df_bf, aes(label=bf10)) + 
    scale_x_continuous(breaks=c()) + 
    facet_wrap(~condition, nrow=1, scales='free_y') + 
    theme_cowplot() + 
    theme(
        axis.title.x = element_blank(),
        axis.line.x = element_blank()
    )

```




---


```{r}

fun_plot <- function(fname, yvar) {
    df <- read.csv(file.path(data_path, fname))
    df$pat <- factor(df$pat)
    df <- filter(df, z_snr > 0)
    ggplot(df, aes(log10(z_snr), .data[[yvar]])) +
        # geom_point(alpha=0.1, color='#701d85') + 
        geom_point(aes(color=pat), alpha=0.1) + 
        geom_hline(yintercept = 0, color='#5e5e5e') + 
        # coord_cartesian(xlim=c(0,100)) + 
        scale_x_reverse() +
        theme_cowplot()
}

```


```{r}

fname <- 'irType-square_apFitMethod-irasa_onlyHarm-false_nrep-50_noiseEffectZscoreACFvsFFT.csv'
df <- read.csv(file.path(data_path, fname))
df$pat <- factor(df$pat)

df$z_meter_fft_subtr_err <- abs(df$z_meter_fft_subtr - df$z_meter_fft_orig)
df$z_meter_acf_subtr_err <- abs(df$z_meter_acf_subtr - df$z_meter_acf_orig)

ggplot(filter(df, selected_for=='fft'), aes(log10(z_snr), z_meter_fft_subtr_err)) +
    geom_point(alpha=0.1, color='#701d85') +
    geom_hline(yintercept = 0, color='#5e5e5e') + 
    scale_x_reverse() +
    theme_cowplot()

ggplot(filter(df, selected_for=='fft'), aes(log10(z_snr), z_meter_fft_subtr)) +
    geom_point(aes(color=pat), alpha=0.1) + 
    geom_hline(yintercept = 0, color='#5e5e5e') + 
    scale_x_reverse() +
    theme_cowplot()



ggplot(filter(df, selected_for=='acf'), aes(log10(z_snr), z_meter_acf_subtr_err)) +
    geom_point(alpha=0.1, color='#701d85') +
    geom_hline(yintercept = 0, color='#5e5e5e') + 
    scale_x_reverse() +
    theme_cowplot()

ggplot(filter(df, selected_for=='acf'), aes(log10(z_snr), z_meter_acf_subtr)) +
    geom_point(aes(color=pat), alpha=0.1) + 
    geom_hline(yintercept = 0, color='#5e5e5e') + 
    scale_x_reverse() +
    theme_cowplot()


df_fft <- filter(df, selected_for=='fft')
df_fft$z_meter_subtr_err <- df_fft$z_meter_fft_subtr_err
    
df_acf <- filter(df, selected_for=='acf')
df_acf$z_meter_subtr_err <- df_acf$z_meter_acf_subtr_err

df <- rbind(df_fft, df_acf)
df$selected_for <- factor(df$selected_for, levels=(c('fft', 'acf')))
ggplot(df, aes(log10(z_snr), z_meter_subtr_err)) +
    geom_point(alpha=0.2, aes(color=selected_for)) +
    geom_hline(yintercept = 0, color='#5e5e5e') + 
    scale_x_reverse() +
    theme_cowplot()

```



```{r}

# fisher-transform
r_to_z <- function(r) .5 * (log(1+r) - log(1-r))
# apply to all relevant columns 
transform_cols <- function(df) {
    df$r_acf_raw <- r_to_z(df$r_acf_raw)
    df$r_acf_subtr <- r_to_z(df$r_acf_subtr)
    df$r_fft_raw <- r_to_z(df$r_fft_raw)
    df$r_fft_subtr <- r_to_z(df$r_fft_subtr)
    return(df)
}


fname <- 'irType-square_apFitMethod-irasa_onlyHarm-false_nrep-50_noiseEffectDistACFvsFFT.csv'
df <- read.csv(file.path(data_path, fname))
df$pat <- factor(df$pat)
# fix negative values before taking log 
df <- filter(df, z_snr > 0)
# # fisher-transform the correlation coefficients
# df <- transform_cols(df)


ggplot(df, aes(log10(z_snr), r_fft_subtr)) +
    geom_point(alpha=0.1, color='#701d85') +
    geom_hline(yintercept = 0, color='#5e5e5e') + 
    scale_x_reverse() +
    theme_cowplot()

ggplot(df, aes(log10(z_snr), r_acf_subtr)) +
    geom_point(alpha=0.1, color='#701d85') +
    geom_hline(yintercept = 0, color='#5e5e5e') + 
    scale_x_reverse() +
    theme_cowplot()


# sigm <- function(x, params) {params['min_'] + (params['max_'] - params['min_']) / (1 + 10.^((params['x50_'] - x) * params['slope_']))}
sigm <- function(x, min_, max_, x50_, slope_) {min_ + (max_ - min_) / (1 + 10.^((x50_ - x) * slope_))}

fit_sigm <- function(x, y, init_params=NULL) {
    df <- data.frame(x=x, y=y)
    if (is_empty(init_params)){
        init_params <- c(quantile(y, 0.05), quantile(y, 0.95), NA, 1)
        if (sum(y == quantile(y, 0.5)) == 0){
            temp <- x[y == quantile(y[2:length(y)], 0.5)]
        } else {
            temp <- x[y == quantile(y, 0.5)]
        }
        init_params[3] <- temp[1]
        names(init_params) <- c('min_', 'max_', 'x50_', 'slope_')
        init_params <- as.list(init_params)        
    }
    m <- nls(y ~ I(min_ + (max_ - min_) / (1 + 10.^((x50_ - x) * slope_))), 
        data=df,
        start=init_params)
    return(m)
}

# x <- runif(100)
# y <- sigm(x, 0, 1, 0.3, 10) + rnorm(100)*0.04
# df <- data.frame(x=x, y=y)
# plot(df)
# params <- fit_sigm(x, y)

df$r_acf_subtr <- abs(df$r_acf_subtr)
df$r_fft_subtr <- abs(df$r_fft_subtr)

m_acf <- fit_sigm(log10(df$z_snr), df$r_acf_subtr)
m_fft <- fit_sigm(log10(df$z_snr), df$r_fft_subtr, 
                       init_params=list('min_'=0, 'max_'=1, 'x50_'=1, 'slope_'=1.5))

ggplot() +
    geom_point(data=df, aes(log10(z_snr), r_acf_subtr), color='#bd3a3a', alpha=0.2) + 
    geom_point(data=df, aes(log10(z_snr), r_fft_subtr), color='#2987b3', alpha=0.2) + 
    geom_function(fun=sigm, args=coef(m_acf), aes(color='acf'), linewidth=2) +
    geom_function(fun=sigm, args=coef(m_fft), aes(color='fft'), linewidth=2) +
    scale_color_manual(name='method', values=c('acf'='#802626', 'fft'='#164961')) + 
    ylab('abs r (re. ground truth)') + 
    theme_cowplot() +
    scale_x_reverse() 

confint(m_acf)
confint(m_fft)





fname <- 'irType-square_apFitMethod-fooof_onlyHarm-false_nrep-50_noiseEffectDistACFvsFFT.csv'
df <- read.csv(file.path(data_path, fname))
df$pat <- factor(df$pat)
# fix negative values before taking log 
df <- filter(df, z_snr > 0)
# # fisher-transform the correlation coefficients
# df <- transform_cols(df)

ggplot(df, aes(log10(z_snr), r_acf_subtr)) +
    geom_point(alpha=0.1, color='#701d85') +
    geom_hline(yintercept = 0, color='#5e5e5e') + 
    scale_x_reverse() +
    theme_cowplot()

```

<br><br><br>

## IR erp2

### FFT  

```{r}
fname <- 'irType-erp2_nrep-100_emphVsNoise.csv'
fun_plot(fname, 'z_meter_fft_raw')
fun_plot(fname, 'z_meter_fft_subtr')
```

### ACF  

```{r}
fun_plot(fname, 'z_meter_acf_raw')
fun_plot(fname, 'z_meter_acf_subtr')
```





<br><br><br>

## IR square

### FFT  

```{r}
fname <- 'irType-square_nrep-100_emphVsNoise.csv'
fun_plot(fname, 'z_meter_fft_raw')
fun_plot(fname, 'z_meter_fft_subtr')
```

### ACF  

```{r}
fun_plot(fname, 'z_meter_acf_raw')
fun_plot(fname, 'z_meter_acf_subtr')
```





```{r}
fname <- 'irType-square_nrep-100_emphVsNoise.csv'
df <- read.csv(file.path(data_path, fname))
df$pat <- factor(df$pat)
df <- filter(df, z_snr > 0)
df$z_snr_log <- log10(df$z_snr)

```

```{r}
m <- lm(z_meter_acf_subtr ~ z_snr_log * z_meter_acf_orig, data=df)
summary(m)
visreg(m, xvar='z_snr_log', by='z_meter_acf_orig', overlay=T)
```

```{r}
m <- lm(z_meter_fft_raw ~ z_snr_log * z_meter_fft_orig, data=df)
summary(m)
visreg(m, xvar='z_snr_log', by='z_meter_fft_orig', overlay=T)
```


























