---
title: "ACF subtr vs. subtr+only_f0_harmonics"
author: "Tomas Lenc"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: 
      collapsed: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('config.R')
source('utils.R')
```


```{r}

data_path <- file.path(experiment_path, 'data')
fname <- 'irType-square_apFitMethod-fooof_noiseEffectDistAllVsOnlyHarm.csv'

df <- read.csv(file.path(data_path, fname))

# convert to factors
df$pat <- factor(df$pat)
df$method <- factor(df$method, levels=c('subtr', 'subtr_only_harm'))

# fix negative values before taking log 
df <- filter(df, z_snr > 0)

# # fisher-transform the correlation coefficients
df$z <- r_to_z(df$r)

cols <- c('subtr'='#2b7557', 'subtr_only_harm'='#711885')

ggplot(df, aes(log10(z_snr), r)) +
    geom_point(alpha=0.4, aes(color=method)) +
    geom_hline(yintercept = 0, color='#5e5e5e') + 
    scale_color_manual(name='method', values=cols) + 
    scale_x_reverse() +
    theme_cowplot()

# fit sigmoids
df_subtr <- filter(df, method=='subtr')
m_subtr <- fit_sigm(log10(df_subtr$z_snr), df_subtr$r)

df_subtr_only_harm <- filter(df, method=='subtr_only_harm')
m_subtr_only_harm <- fit_sigm(log10(df_subtr_only_harm$z_snr), df_subtr_only_harm$r)

# print confidence intervals on paramter estimates 
confint(m_subtr)
confint(m_subtr_only_harm)

# plot 
ggplot() +
    geom_point(data=df_subtr, aes(log10(z_snr), r), 
               color=lighten(cols['subtr'], 0.2), alpha=0.2) + 
    geom_point(data=df_subtr_only_harm, aes(log10(z_snr), r), 
               color=lighten(cols['subtr_only_harm'], 0.2), alpha=0.2) + 
    geom_function(fun=sigm, args=coef(m_subtr), aes(color='subtr'), linewidth=2) +
    geom_function(fun=sigm, args=coef(m_subtr_only_harm), aes(color='subtr_only_harm'), linewidth=2) +
    geom_hline(yintercept = 0, color='#5e5e5e') + 
    scale_color_manual(name='method', values=cols) + 
    scale_y_continuous(limits=c(-1, 1), breaks=c(-1, 0, 1)) + 
    ylab('r with ground truth') + 
    theme_cowplot() +
    scale_x_reverse() 


```
