---
title: "Autocorrelation SNR vs. number of lags/frex"
author: "Tomas Lenc"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: 
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source('config.R')
source('figures.R')
source('utils.R')

```

```{r}
# list.files(data_path)
```


<br><br><br>

---

## IR square

```{r}

df <- read.csv(file.path(data_path, 
                         sprintf('irType-square_nrep-500_snrVsNlagsNfrex.csv')))

df$max_lag <- factor(df$max_lag)
df$max_freq <- factor(df$max_freq)
df$snr <- factor(round(df$snr, 1))
df$sample <- factor(df$sample)
```

<br><br>

### ACF  

```{r, fig.width=10, fig.height=5.5}
p1 <- plot_data(df,  'z_meter_acf_subtr', 'z_meter_acf_orig', 'max_lag')
p2 <- plot_bias_var(df,  'z_meter_acf_subtr', 'z_meter_acf_orig', 'max_lag')
plot_grid(p1, p2, rel_widths=c(60, 40))
```


<br><br>

### FFT

```{r, fig.width=10, fig.height=5.5}
p1 <- plot_data(df,  'z_meter_fft_subtr', 'z_meter_fft_orig', 'max_freq')
p2 <- plot_bias_var(df,  'z_meter_fft_subtr', 'z_meter_fft_orig', 'max_freq')
plot_grid(p1, p2, rel_widths=c(60, 40))
```




<br><br><br>

---

## IR erp2

```{r}

df <- read.csv(file.path(data_path, 
                         sprintf('irType-erp2_nrep-500_snrVsNlagsNfrex.csv')))

df$max_lag <- factor(df$max_lag)
df$max_freq <- factor(df$max_freq)
df$snr <- factor(round(df$snr, 1))
df$sample <- factor(df$sample)
```

<br><br>

### ACF  

```{r, fig.width=10, fig.height=5.5}
p1 <- plot_data(df,  'z_meter_acf_subtr', 'z_meter_acf_orig', 'max_lag')
p2 <- plot_bias_var(df,  'z_meter_acf_subtr', 'z_meter_acf_orig', 'max_lag')
plot_grid(p1, p2, rel_widths=c(60, 40))
```


<br><br>

### FFT

```{r, fig.width=10, fig.height=5.5}
p1 <- plot_data(df,  'z_meter_fft_subtr', 'z_meter_fft_orig', 'max_freq')
p2 <- plot_bias_var(df,  'z_meter_fft_subtr', 'z_meter_fft_orig', 'max_freq')
plot_grid(p1, p2, rel_widths=c(60, 40))
```
