function f = plot_nonrep_seq(par)

par.n_cycles = 1; 

par.pat = randsample([0, 1], 240, true); % nonrepeating sequence
par.pat(1) = 1; 
    
beat_idx = [1 : 4 : length(par.pat)];
idx = randsample(length(beat_idx), length(beat_idx) / 2); 
beat_idx_sound = beat_idx(idx); 
par.pat(beat_idx_sound) = 1; 

% make whole signal 
[x, t] = get_s(...
                par.pat, ...
                par.grid_ioi, ...
                par.fs, ...
                'n_cycles', par.n_cycles, ...
                'ir', par.ir ...
                );

% get acf withuout aperiodic subtraction    
[acf, lags, ~, mX, freq] = get_acf(x, par.fs);    

%%

if par.max_lag <= 5
    fig_size = [146 1340 900 150]; 
    example_subplot_proportions = [60, 15, 25];
else
    fig_size = [146 1340 1329 150]; 
    example_subplot_proportions = [35, 10, 55];
end

f = figure('color','white', ...
           'position', fig_size); 
       
pnl = panel(f); 

pnl.pack('v', [20, 80]); 

pnl(2).pack('v', 1); 

plot_example(x, t, acf, lags, [], mX, freq, ...
             par.lags_meter_rel, par.lags_meter_unrel, ...
             par.freq_meter_rel, par.freq_meter_unrel, ...
             'pnl', pnl(2, 1), ...
             'subplot_proportions', example_subplot_proportions, ...
             'max_lag', par.max_lag, ...
             'max_freq', par.max_freq_plot, ...
             'plot_time_xaxis', true, ...
             'plot_xlabels', true, ...
             'plot_xticks', true, ...
             'plot_features', false, ...
             'time_col', [0 0 0], ...
             'prec', 1e6, ...
             'linew_acf', 1.4, ...
             'fontsize', par.fontsize, ...
             'normalize_acf_for_plotting', false);        
         
         
         
